---
apiVersion: v1
kind: Pod
metadata:
  name: soccer-vote-app-pod
spec:
  containers:
    - name: soccer-vote-app
      image: quay.io/cclyburn/devbcn-demo:latest
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /votes
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /votes
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: soccer-vote-app-service
spec:
  selector:
    app: soccer-vote-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 